import type { MetadataRoute } from "next";

import { siteConfig } from "@/config/site";

/**
 * The web app manifest, served at `/manifest.webmanifest`.
 *
 * Both purposes are supplied for a reason: `maskable` icons are cropped to the
 * launcher's own shape (circle on Pixel, squircle on Samsung), so they carry extra
 * padding, while `any` icons are drawn as-is and would look shrunken if reused.
 * Every file here is generated by `scripts/generate-icons.mjs`.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${siteConfig.name} — ${siteConfig.tagline}`,
    short_name: siteConfig.shortName,
    description: siteConfig.description,
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: "#0d1017",
    theme_color: "#0d1017",
    orientation: "portrait-primary",
    categories: ["productivity", "utilities", "social"],
    icons: [
      { src: "/brand/favicon.svg", sizes: "any", type: "image/svg+xml" },
      { src: "/brand/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/brand/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/brand/icon-maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/brand/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
