/**
 * Reading a sitemap, and sorting its URLs into buckets.
 *
 * Split out from `sitemap-report.ts` so it can be tested without a server, an API
 * or a fetch — this is the half with the fiddly details in it (XML entities in the
 * filter URLs, and the difference between a listing and a facet of one), and the
 * half where a mistake is silent rather than loud.
 */

import type { SitemapEntry } from "./types";

/**
 * A regex, not a parser.
 *
 * This file is generated by `app/sitemap.ts` a few lines away, so its shape is not
 * an unknown — one flat `<urlset>` of `<url>` elements with no attributes, no
 * namespaced extensions and no CDATA. Pulling in an XML dependency to read our own
 * output would be the odd choice. Anything unparseable simply does not appear,
 * which the served-versus-expected count then shows up as a difference.
 */
export function parseSitemap(xml: string): SitemapEntry[] {
  const entries: SitemapEntry[] = [];

  for (const block of xml.match(/<url>[\s\S]*?<\/url>/g) ?? []) {
    const loc = tag(block, "loc");
    if (loc === null) continue;

    const priority = tag(block, "priority");

    entries.push({
      loc,
      path: pathOf(loc),
      lastmod: tag(block, "lastmod"),
      changefreq: tag(block, "changefreq"),
      priority: priority === null ? null : Number(priority),
    });
  }

  return entries;
}

function tag(block: string, name: string): string | null {
  const match = block.match(new RegExp(`<${name}>([\\s\\S]*?)</${name}>`));

  return match ? decodeEntities(match[1].trim()) : null;
}

/** The five XML predefined entities. `&amp;` is the one that matters: filter URLs carry `?category=`. */
function decodeEntities(value: string): string {
  return value
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&");
}

/**
 * Which bucket a URL belongs to.
 *
 * Filtered listings are counted apart from the pages they filter: `/tools` and
 * `/tools?category=youtube` are one page and one facet of it, and folding them
 * together would hide the case where every facet is present and every tool is gone.
 */
export function sectionOf(path: string): string {
  if (isHome(path)) return "home";

  const [pathname, query] = path.split("?");
  const segments = pathname.split("/").filter(Boolean);

  if (segments[0] === "tools") {
    if (segments.length > 1) return "tools";
    return query ? "tool-filters" : "static";
  }

  if (segments[0] === "blog") {
    if (segments.length > 1) return "blog";
    return query ? "blog-filters" : "static";
  }

  if (segments[0] === "changelog") return "changelog";

  return "static";
}

export function isHome(path: string): boolean {
  return path === "/" || path === "";
}

/** The part worth reading in a table — everything after the origin. */
export function pathOf(loc: string): string {
  try {
    const parsed = new URL(loc);

    return `${parsed.pathname}${parsed.search}`;
  } catch {
    return loc;
  }
}
