/**
 * Generates every favicon, app icon and logo file in `public/brand` (plus the two
 * favicon.ico files the frameworks serve from a fixed path) from one SVG source.
 *
 *     node scripts/generate-icons.mjs
 *
 * Re-run it after editing `scripts/brand-mark.mjs`; nothing here is hand-drawn, so
 * the checked-in binaries and the mark can never drift apart.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import sharp from "sharp";

import { C, markPaths, markSvg, tileSvg } from "./brand-mark.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "public", "brand");
mkdirSync(out, { recursive: true });

const written = [];
const write = (rel, buf) => {
  const path = join(root, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, buf);
  written.push(`${rel}  ${(buf.length / 1024).toFixed(1)} KB`);
};

const png = (svg, size) =>
  sharp(Buffer.from(svg)).resize(size, size, { fit: "contain" }).png({ compressionLevel: 9 }).toBuffer();

/**
 * ICO is a header plus a directory plus the images; PNG-compressed entries are
 * legal since Vista and are what every modern browser reads, so there is no need
 * for a BMP encoder here.
 */
function ico(entries) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(entries.length, 4);
  let offset = 6 + entries.length * 16;
  const dir = [];
  for (const { size, data } of entries) {
    const e = Buffer.alloc(16);
    e.writeUInt8(size >= 256 ? 0 : size, 0);
    e.writeUInt8(size >= 256 ? 0 : size, 1);
    e.writeUInt8(0, 2);
    e.writeUInt8(0, 3);
    e.writeUInt16LE(1, 4);
    e.writeUInt16LE(32, 6);
    e.writeUInt32LE(data.length, 8);
    e.writeUInt32LE(offset, 12);
    dir.push(e);
    offset += data.length;
  }
  return Buffer.concat([header, ...dir, ...entries.map((x) => x.data)]);
}

/** The horizontal lockup. Text stays live so it scales without a raster step. */
function lockup(fg, accent) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 208 32" width="208" height="32" role="img" aria-label="MetaCreator.Dev">
  ${markSvg().replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "")}
  <text x="42" y="21.5" font-family="'DM Sans','Helvetica Neue',Arial,sans-serif" font-size="16" font-weight="600" letter-spacing="-0.4" fill="${fg}">MetaCreator</text>
  <text x="151" y="21.5" font-family="'JetBrains Mono','SF Mono',ui-monospace,monospace" font-size="13.5" fill="${accent}">.dev</text>
</svg>`;
}

const svgs = {
  "public/brand/logo-mark.svg": markSvg(),
  "public/brand/logo-mark-flat.svg": markSvg(true),
  "public/brand/favicon.svg": markSvg(),
  "public/brand/logo-lockup-light.svg": lockup("#141821", C.signal500),
  "public/brand/logo-lockup-dark.svg": lockup(C.fg, C.signal400),
  "public/brand/icon-tile.svg": tileSvg({ size: 512 }),
};
for (const [rel, svg] of Object.entries(svgs)) write(rel, Buffer.from(svg));

/** Bare mark on transparency — browser tabs, which draw their own background. */
const bare = [16, 32, 48, 64, 96, 128, 256];
/** Mark on the dark ground — anything that composites onto an unknown surface. */
const tiles = [
  ["apple-touch-icon", 180, { scale: 0.62, square: true }],
  ["apple-touch-icon-152", 152, { scale: 0.62, square: true }],
  ["apple-touch-icon-167", 167, { scale: 0.62, square: true }],
  ["icon-192", 192, { scale: 0.66 }],
  ["icon-512", 512, { scale: 0.66 }],
  // Maskable icons get cropped to the launcher's shape, so the mark sits inside
  // the 80% safe zone and the ground runs edge to edge.
  ["icon-maskable-192", 192, { scale: 0.5, radius: 0 }],
  ["icon-maskable-512", 512, { scale: 0.5, radius: 0 }],
  ["mstile-150", 150, { scale: 0.62, square: true }],
];

const icoParts = [];
for (const size of bare) {
  const data = await png(markSvg(size <= 32), size);
  write(`public/brand/favicon-${size}x${size}.png`, data);
  if ([16, 32, 48].includes(size)) icoParts.push({ size, data });
}
for (const [name, size, opts] of tiles) {
  write(`public/brand/${name}.png`, await png(tileSvg({ size: 512, ...opts }), size));
}

/**
 * The geometry, as a module the app can import. `<Logo>` paints the mark in theme
 * tokens rather than fixed hex, so it needs the paths rather than a finished SVG;
 * the OG card cannot use CSS variables at all and takes the data URI. Emitting
 * both here is what keeps every surface on one drawing.
 */
const { rod, sparks } = markPaths();
const list = (arr) => arr.map((d) => `\n  ${JSON.stringify(d)},`).join("");
write(
  "src/lib/brand-mark.generated.ts",
  Buffer.from(`// GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Change the geometry in scripts/brand-mark.mjs and re-run the script.

/** The tapered wand. */
export const MARK_ROD = ${JSON.stringify(rod)};

/** The four sparks it throws, largest first. */
export const MARK_SPARKS = [${list(sparks)}\n] as const;

/** The full mark with its own palette baked in, for contexts with no CSS. */
export const MARK_DATA_URI =
  "data:image/svg+xml;base64,${Buffer.from(markSvg()).toString("base64")}";
`),
);

// Both frameworks serve a favicon from a path they control; keep them identical.
const icoBuf = ico(icoParts);
write("src/app/favicon.ico", icoBuf);
write("../api/public/favicon.ico", icoBuf);

// Raster lockups for contexts that will not take an SVG (email, README, docs).
for (const theme of ["light", "dark"]) {
  for (const s of [1, 2, 3]) {
    write(
      `public/brand/logo-lockup-${theme}${s > 1 ? `@${s}x` : ""}.png`,
      await sharp(Buffer.from(svgs[`public/brand/logo-lockup-${theme}.svg`]))
        .resize({ width: 208 * s })
        .png({ compressionLevel: 9 })
        .toBuffer(),
    );
  }
}

console.log(written.join("\n"));
console.log(`\n${written.length} files written.`);
