#!/usr/bin/env python3
"""Generates a writing brief per planned post, and the empty post file to fill in.

Briefs are generated, never hand-edited: the plan is the source of truth, so a
brief that disagrees with plan/posts.json is a brief that is wrong.

    python3 scripts/gen_briefs.py --wave 1
    python3 scripts/gen_briefs.py --wave 1 --stub    # also write posts/<slug>.md skeletons
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from _common import ROOT, clusters, posts, tools

ARCHETYPE_SHAPE = {
    "pillar": ["What the reader is trying to do", "How the system actually works",
               "The parts, one H2 each, every one linking down to its spoke",
               "What to do first", "FAQ"],
    "howto": ["The one-sentence answer", "What you need", "Steps, numbered",
              "The tool that does it for you", "What goes wrong", "FAQ"],
    "explainer": ["The short answer, in the first 40 words", "Why the number/limit is what it is",
                  "What it means for your posts", "Edge cases", "FAQ"],
    "comparison": ["The recommendation up front", "The criteria, stated before the comparison",
                   "Option by option", "A table", "When each one wins", "FAQ"],
    "benchmarks": ["The headline numbers, with the date and the source",
                   "Method: what was measured and what was not", "By follower tier",
                   "How to compare yourself honestly", "FAQ"],
    "templates": ["The template, first, before any preamble", "How to fill each part in",
                  "A worked example", "The tool that generates it", "FAQ"],
    "troubleshooting": ["The ordered list of causes, most likely first",
                        "One H2 per cause with the check that confirms it",
                        "What to do when none of them apply", "FAQ"],
    "guide": ["Scope", "Section per subtopic", "Next steps", "FAQ"],
}

BRIEF = """# Brief - {title}

<!-- Generated by scripts/gen_briefs.py from plan/posts.json. Do not edit by hand. -->

|  |  |
| --- | --- |
| Post id | `{id}` |
| Cluster | {cluster_name} (`{cluster}`) |
| Pillar | {pillar_link} |
| Wave | {wave} |
| Archetype | {archetype} |
| URL | `{url}` |
| Category | `{category}` |
| Tags | {tags} |
| Target length | ~{target_words} words |
| Funnel stage | {funnel} |

## Search intent

Primary keyword: **{primary_keyword}**
Secondary: {secondary}

Write for the person who typed the primary keyword and wants to stop typing. The
first 40 words answer them; everything after that is for the reader who needs the
detail. If the honest answer is "it depends", say what it depends on in that first
paragraph rather than making them scroll for it.

## Required outline

{outline}

## Tools this post exists to feed

{tool_lines}

At least one `[[tool:slug]]` card goes in the body at the moment the reader needs
it - not parked at the end. Link `/tools/<slug>` in prose as well, with the tool's
own name as the anchor.

## Internal links

- Up to the pillar: {pillar_link}
- Sideways to two or three siblings in the same cluster (pick from the cluster list
  in `plan/posts.json`); only link to posts that are already published.
- Down from the pillar: add this post to the pillar's section when it goes live.

## Non-negotiables

- Every platform limit, threshold or payout figure carries the date it was checked
  and a link to the platform's own documentation. Numbers age; undated numbers rot.
- No invented search volumes, no invented benchmarks. If we did not measure it, we
  attribute it or we leave it out.
- A tool of ours is described as what it does, never as "the best". The reader can
  see the button.
- Run `python3 scripts/audit.py posts/{slug}.md` before publishing.
"""

STUB = """---
{header}
---
{lead}

## {first_h2}

[[tool:{tool}]]

:::faq
Q: 
A: 
:::
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--wave", type=int, action="append", help="limit to a wave (repeatable)")
    parser.add_argument("--stub", action="store_true", help="also create empty post files")
    args = parser.parse_args()

    CL, TOOLS = clusters(), tools()
    rows = [p for p in posts() if not args.wave or p["wave"] in args.wave]
    pillars = {c["pillar"] for c in CL.values()}
    (ROOT / "briefs").mkdir(exist_ok=True)
    (ROOT / "posts").mkdir(exist_ok=True)

    for p in rows:
        cluster = CL[p["cluster"]]
        is_pillar = p["slug"] in pillars
        pillar_link = "this post is the pillar" if is_pillar else f"[/blog/{cluster['pillar']}](/blog/{cluster['pillar']})"
        outline = "\n".join(f"{i}. {s}" for i, s in
                            enumerate(ARCHETYPE_SHAPE.get(p["archetype"], ARCHETYPE_SHAPE["explainer"]), 1))
        tool_lines = "\n".join(
            f"- [`{t}`](/tools/{t}) - {TOOLS[t]['name']}: {TOOLS[t]['tagline']}" for t in p["tools"]
        ) or "- (none - this post carries no tool; justify that in review or drop the post)"
        fields = dict(p)
        fields.update(
            cluster_name=cluster["name"], pillar_link=pillar_link, outline=outline,
            tool_lines=tool_lines, tags=", ".join(f"`{t}`" for t in p["tags"]),
            secondary=", ".join(p["secondary_keywords"]) or "-",
        )
        brief = BRIEF.format(**fields)
        (ROOT / "briefs" / f"{p['slug']}.md").write_text(brief)

        stub_path = ROOT / "posts" / f"{p['slug']}.md"
        if args.stub and not stub_path.exists():
            header = json.dumps({
                "id": p["id"], "slug": p["slug"], "title": p["title"],
                "excerpt": "", "category": p["category"],
                "categories": [], "tags": p["tags"],
                "primary_keyword": p["primary_keyword"], "status": "draft",
                "seo": {"title": p["title"], "description": "",
                        "focus_keyword": p["primary_keyword"],
                        "twitter_card": "summary_large_image", "schema_type": "BlogPosting"},
            }, indent=1)
            stub_path.write_text(STUB.format(
                header=header, lead=f"<!-- 40-word answer containing '{p['primary_keyword']}' -->",
                first_h2="TODO", tool=(p["tools"] or ["engagement-rate-calculator"])[0]))

    print(f"wrote {len(rows)} briefs to briefs/" + (" and stubs to posts/" if args.stub else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
