#!/usr/bin/env python3
"""Renders plan/keyword-map.csv and strategy/04-editorial-calendar.md from the plan.

Both are generated views. Edit plan/posts.json, re-run this, commit the diff.
"""
from __future__ import annotations

import csv
from collections import defaultdict

from _common import ROOT, clusters, posts

CSV_FIELDS = ["id", "wave", "cluster", "archetype", "funnel", "primary_keyword",
              "secondary_keywords", "url", "title", "category", "tags", "tools",
              "target_words", "status"]


def write_csv() -> None:
    with (ROOT / "plan" / "keyword-map.csv").open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=CSV_FIELDS)
        writer.writeheader()
        for p in sorted(posts(), key=lambda r: (r["wave"], r["cluster"], r["id"])):
            row = {k: p[k] for k in CSV_FIELDS}
            for key in ("secondary_keywords", "tags", "tools"):
                row[key] = "; ".join(p[key])
            writer.writerow(row)


HEADER = """# 04 - Editorial calendar

<!-- Generated by scripts/gen_calendar.py from plan/posts.json. Do not edit by hand. -->

Six waves, one per month. A wave is a batch, not a drip: search engines reward a
site that covers a subject completely far faster than one that publishes the same
number of posts scattered across ten subjects.

**Cadence.** {per_week:.0f} posts a week sustained, published Tuesday and Thursday
mornings, with the pillar of each wave going out first so its spokes have something
to link up to on day one.

**The rule that outranks the calendar.** A wave is finished when its pillar and
every spoke is live *and interlinked*. A half-linked cluster is worth less than a
smaller complete one, so cut scope inside a wave before you cut the linking pass.

| Wave | Month | Posts | Words | Clusters |
| --- | --- | --- | --- | --- |
{summary}

"""


def write_calendar() -> None:
    CL = clusters()
    by_wave: dict[int, list[dict]] = defaultdict(list)
    for p in posts():
        by_wave[p["wave"]].append(p)

    total = sum(len(v) for v in by_wave.values())
    summary = "\n".join(
        f"| {w} | Month {w} | {len(rows)} | {sum(r['target_words'] for r in rows):,} | "
        f"{', '.join(sorted({CL[r['cluster']]['name'] for r in rows}))} |"
        for w, rows in sorted(by_wave.items())
    )
    out = [HEADER.format(summary=summary, per_week=total / 26)]

    pillars = {c["pillar"] for c in CL.values()}
    for wave, rows in sorted(by_wave.items()):
        out.append(f"## Wave {wave} - Month {wave}\n")
        for cluster_id in sorted({r["cluster"] for r in rows}):
            cluster = CL[cluster_id]
            out.append(f"### {cluster['name']}\n")
            out.append("| # | Post | Primary keyword | Type | Words | Tools it feeds |")
            out.append("| --- | --- | --- | --- | --- | --- |")
            for r in sorted(rows, key=lambda x: (x["slug"] not in pillars, x["id"])):
                if r["cluster"] != cluster_id:
                    continue
                mark = " **(pillar)**" if r["slug"] in pillars else ""
                tools = ", ".join(f"`{t}`" for t in r["tools"][:3]) or "-"
                out.append(f"| `{r['id']}` | [{r['title']}]({r['url']}){mark} | {r['primary_keyword']} "
                           f"| {r['archetype']} | {r['target_words']} | {tools} |")
            out.append("")
    (ROOT / "strategy" / "04-editorial-calendar.md").write_text("\n".join(out))


if __name__ == "__main__":
    write_csv()
    write_calendar()
    print("wrote plan/keyword-map.csv and strategy/04-editorial-calendar.md")
